on: [push]

jobs:
  create_issues_action:
    runs-on: ubuntu-latest
    name: create issues action 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create issues action
        uses: ./ # Use an action in the root directory
        with:
          token: ${{secrets.TOKEN}}